name: 'pychecker'
description: 'GitHub Action for Python code check'
inputs:
  path:
    description: 'check path'
    required: false
    default: './'
outputs:
  output:
    description: 'The output of pychecker'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
